api_key = "2SRiDe6TPL9jyzse8XEkhpeJzx9udw1Yqd5hUyAKNjCKri5PBALyyRhQflVBPGCx"
poll_rate = 1800

[[domain]]
domain = "ganners.co.uk"
subdomain = ""

[[domain]]
domain = "ganners.co.uk"
subdomain = "www"

[[domain]]
domain = "ganners.co.uk"
subdomain = "home"
